### ISSUE TITLE
Add "replace" for kzykhys/parallel

### ISSUE THREAD

**Issue by mbrodala** [tiagobutzke/PHParallel#4]
Currently one cannot install the package `tiagobutzke/phparallel` if any other package depends on `kzykhys/parallel`. More precisely: installation works but the Composer autoload will complain about duplicate autoload entries; the first one wins in this case.

Please add a `replace` to your `composer.json` and make a new release. :-)

An alternative would be to change the namespace of all classes.

**Comment by tiagobutzke** [comment]
Do you mind send a pull request for this?

**Comment by mbrodala** [comment]
There we go.

**Comment by tiagobutzke** [comment]
Thanks man! :)
